### ISSUE TITLE
DeRecStatusNotifications are incomplete

### ISSUE THREAD

**Issue by diptimahamuni** [jorabin/derec-tests#12]
**Helper notifications:**
Ideally we want to know:
- When Helper is paired (successfully or unsuccessfully) - defined as AVAILABLE or NOT AVAILABLE, and
- Whether they are responding to verification messages or not (HEALTHY or NOT HEALTHY). 

In DeRecStatusNotification, we should add notifications for when a helper is available/not available, and a helper is healthy/not healthy.

**Pairing notifications:**
- During pairing, one would want to know that the person they are pairing with is in recovery mode, to help them be extra vigilant about who they are pairing with. A notification should be added to accommodate that.

**Recovery notifications:**
- We should have a notification for sharer when the secret has been recovered.

**Comment by lbaird** [comment]
Rename HELPER_READY to HELPER_PAIRED

We just will add:

HELPER_HEALTHY
HELPER_NOT_HEALTHY
SECRET_RECOVERED

**Comment by lbaird** [comment]
Looks good
