### ISSUE TITLE
Is there a better word for secret recoverability than "available"

### ISSUE THREAD

**Issue by jorabin** [jorabin/derec-tests#9]
to describe the success of the last update to the secret

**Comment by jorabin** [comment]
There are a number of places (notifications, status checks etc.) using the word _available_ (e.g. `version.isAvailable()`, `VERIFY_AVAILABLE`, `UPDATE_AVAILABLE`) to signify that a quorum of responses have been received and that the last known state is that a recovery operation will be successful.

We are looking for an alternative word. One that comes to mind is _recoverable_ the problem with that being that a notification of, say, `UPDATE_UNRECOVERABLE` seems to signify more than it is intended to, inasmuch as it's a temporary condition. UNAVAILABLE connotes this sense much more clearly.

Propose to use AVAILABLE and UNAVAILABLE to refer to the state of a secret/version and cease using it in other contexts such as the status of a helper, which will be PAIRED, UNPAIRED ...

**Comment by lbaird** [comment]
I agree it's better to use different terms for the different conditions. I agree with the suggested terms. I'd be fine with either AVAILABLE or RECOVERABLE. Either is fine. We should choose a name for each of these numbered conditions. 

A particular version of a secret can be:

1. Shared with a sufficient number of helpers that we are confident it could be recovered (i.e., confirmations received from a quorum that equals the threshold to reconstruct, plus a safety margin)

2. Not confirmed yet by a quorum.

For a given helper for a given secret, it can be:

3. Not yet paired (or no longer paired, after receiving confirmation of an unpair request).

4. Still paired, but an unpairing request has been sent, without confirmation yet.

5. Paired

6. Has not communicated in a long time (longer than a threshold period set by the app). Share updates will still be sent to them, but we will not count them when counting whether we have a reconstruction quorum. 

7. Has communicated recently, so counts as part of quorum. 

Any naming convention is fine, if it's clear in all these cases. Perhaps the above suggestion would lead to something like this:

1. AVAILABLE
2. UNAVAILABLE

3. UNPAIRED
4. UNPAIRING
5. PAIRED

6. UNHEALTHY
7. HEALTHY

At any given moment, a share version is in one of {1, 2}. 

At any given moment, a sharer’s opinion about a given helper for a given share will be in exactly one of {3, 4, 5}, and will be in exactly one of {6, 7}.

**Comment by jorabin** [comment]
There may be value in considering this in a slightly broader way. 

### Secret Status

1. Fewer paired helpers than the required minimum threshold - UNREADY?
2. Fewer healthy helpers than the current threshold (implies a possible re-share) - UNAVAILABLE
3. Fewer healthy helpers than the current threshold plus safety margin (running on reserve tank) - CAUTION?
4. Healthy helper greater than or equal to threshold plus margin - AVAILABLE

### Helper Status
These are the statuses in DeRecHelperStatus

1. Not yet invited to pair - NONE
3. Invited not responded - INVITED
4. Responded negatively - REFUSED
5. Responded positively - PAIRED
    1. Responded to last request - HEALTHY (not in enum at the moment)
    2. No response after timeout/retry threshold - UNHEALTHY (not in enum at the moment)
7. Helper requested unpairing - GONE
8. Sharer unpair requested, no response yet - PENDING_REMOVAL
9. Unpaired by response REMOVED
10. Unpaired by timeout - FAILED

### Status Notifications

These are defined in DeRecStatusNotification

1.    UPDATE_PROGRESS(UNCLASSIFIED), // a vehicle for saying things about an update
2.    UPDATE_AVAILABLE(NORMAL), // a sufficient number of acknowledgements have been received for an update to consider it recoverable
3.    UPDATE_FAILED(ERROR), // update can't reach quorum
4.    UPDATE_COMPLETE(NORMAL), // all update requests have been replied to, or failed
5.    VERIFY_PROGRESS(UNCLASSIFIED), // a vehicle for saying things about a verify
6.    VERIFY_AVAILABLE(NORMAL), // a sufficient number of acknowledgements have been received for verify
7.    VERIFY_FAILED(ERROR), // verification can't reach quorum
8.    VERIFY_COMPLETE(NORMAL), // all update requests have been replied to, or failed
9.    RECOVERY_PROGRESS(UNCLASSIFIED),
10.    RECOVERY_AVAILABLE(NORMAL), // a sufficient number of responses have been received to reconstruct secret
11.    RECOVERY_FAILED(ERROR), // the secret cannot be recovered at the present time
12.    RECOVERY_COMPLETE(NORMAL), // all  requests have been replied to, or failed
13.    HELPER_PAIRED(NORMAL), // helper accepted a pair request
14.    HELPER_NOT_PAIRED(ERROR), // pairing failed
15.    HELPER_UNHEALTHY(WARNING), // a healthy helper has become unhealthy
16.    HELPER_HEALTHY(NORMAL), // an unhealthy helper has become healthy
17.    HELPER_UNPAIRED(NORMAL), // an unpair action successfully or unsuccessfully completed for this helper
18.    SECRET_UNAVAILABLE(ERROR), // a secret that had previously been usable is now not usable
19.    SECRET_AVAILABLE(NORMAL); // a secret is now available for use, i.e. a sufficient number of helpers can receive updates and support recovery

**Comment by lbaird** [comment]
All 4+8 of those are fine. 

If a helper is PAIRED or PENDING_REMOVAL, either way, they can be either HEALTHY or UNHEALTHY.  We could create 4 different statuses for all 4 combinations, but then if we ever add a new status, we'd also have to add the HEALTHY and UNHEALTHY version of it.  That would be ugly.

A cleaner approach is to have a "status" that is one of the 8 listed, and also have a "health" that is either HEALTHY or UNHEALTHY.  For the latter, there's no need for an enum. It can just be a boolean.  

So a given helper for a given secret would have a `getStatus` method returning an enum with 8 possible values, and would also have an `isHealthy` method that returns true or false.  So then there's no need to have HEALTHY or UNHEALTHY in the enum.

**Comment by jorabin** [comment]
Agree that it's better to split the concept. Might want three health statuses - HEALTY, RETRY and UNHEALTHY? Or should that be SICK for RETRY.

**Comment by lbaird** [comment]
Change:

`getHealth` will return an enum with `HEALTHY`, `UNHEALTHY`, `SICKENING`.
